### ISSUE TITLE
Where is the cSpec.h?

### ISSUE THREAD

**Issue by chenyulue** [Oblivious-Oblivious/cSpec#1]
In your repo there isn't `cSpec.h` file.

**Comment by Oblivious-Oblivious** [comment]
You are supposed to run the "./compile" script in a *nix system to get all header files merged into cSpec.h.

For context this project is stuck in the middle of a refactoring to work with the [Emeralds](https://github.com/Oblivious-Oblivious/Emeralds) package manager that's why it is unclear for now.

**Comment by Oblivious-Oblivious** [comment]
Fixed with latest commit, cSpec.h exists in the export directory.

**Comment by chenyulue** [comment]
Thanks for your work!

**Comment by chenyulue** [comment]
BTW, in `cSpec.h` there is a warning telling `cSpec.h:1204:5: warning: implicit declaration of function 'localtime_r'; did you mean 'localtime_s'? [-Wimplicit-function-declaration]`. I'm not sure whether `localtime_r` is a typo. Should it be `localtime_s`? If I change `localtime_r` to `localtime_s`, everything seems OK.

One more thing is that when compiling suppression of some warning such as `Wno-pointer-to-int-cast` etc is used to get a clean compiling result. Is it possible to eliminate those warnings by refactoring code?

**Comment by Oblivious-Oblivious** [comment]
I think the `localtime_r` error depends on operating system and compiler used.  For ease of use I picked clang on MacOS, but I'll be implementing continuous integration on windows and linux soon.

It's true I am using many warnings which I plan to remove, simple casting errors can probably be fixed using casting from (void*), others come up when I'm mixing custom struct strings with (char*).  I plan on revisiting the library the following weeks fixing these.  Thanks for using the lib.
